#!/usr/bin/env bash

function run {
    if ! pgrep $1 ;
    then
        $@&

    fi
}

run sxhkd -c /home/juanc/.config/bspwm/sxhkd/sxhkdrc &

# wallpaper
run /home/juanc/.config/bspwm/scripts/setwallpaper -r

run picom --config $HOME/.config/bspwm/picom.conf &